<?php

namespace Hugo\PlatformBundle\Entity;

/**
 * ClimateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClimateRepository extends \Doctrine\ORM\EntityRepository
{
}
