<?php

namespace Hugo\PlatformBundle\Entity;

/**
 * ImageobjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageobjRepository extends \Doctrine\ORM\EntityRepository
{
}
