<?php

namespace Hugo\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends \Doctrine\ORM\EntityRepository
{

	public function getObjects()
  	{
    $qb = $this->createQueryBuilder('o');
      // Jointure sur l'attribut image
      $qb
      ->leftJoin('o.imageobj', 'i')
      ->addSelect('i')
      // Jointure sur l'attribut categories
      ->leftJoin('o.categories', 'c')
      ->addSelect('c')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;

  	}


  public function getObjectsWithCategories(array $categoryNames)
  {
    $qb = $this->createQueryBuilder('o');

      // Jointure sur l'attribut image
      $qb
      ->leftJoin('o.imageobj', 'i')
      ->addSelect('i')
      // Jointure sur l'attribut categories
      ->leftJoin('o.categories', 'c')
      ->addSelect('c')
      ->where($qb->expr()->in('c.name', $categoryNames))
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}