<?php

namespace Hugo\PlatformBundle\Entity;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends \Doctrine\ORM\EntityRepository
{
}
