services:
#    hugo_user.example:
#        class: Hugo\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    hugo_user.registration.form.type:
        class: Hugo\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: hugo_user_registration }

    hugo_user.profile.form.type:
        class: Hugo\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: hugo_user_profile }

    authentication_handler:
        class:        Hugo\UserBundle\Handler\AuthenticationHandler
        arguments:    [@router, @security.context, @fos_user.user_manager, @service_container]